name: ci-synapse

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'synapse/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: synapse/synapse-via/synapse-via.sqlproj
      PROJECT_PATH: synapse/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.sqlproj
      DACPAC_PATH: synapse/${{ env.PROJECT_NAME }}/bin/Debug/${{ env.PROJECT_NAME }}.dacpac

    steps:
      - uses: actions/checkout@v2

      - name: Install sqlpackage
        run: |
          curl -Lo sqlpackage-linux.zip https://aka.ms/sqlpackage-linux
          unzip -o sqlpackage-linux.zip -d /opt/sqlpackage/
          chmod +x /opt/sqlpackage/*
          sudo rm -f /bin/sqlpackage
          sudo ln -s /opt/sqlpackage/sqlpackage /bin/sqlpackage
          sudo rm -rf sqlpackage-linux.zip

      - name: Install dotnet
        run: |
          wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
          sudo dpkg -i packages-microsoft-prod.deb && \
          rm packages-microsoft-prod.deb

          sudo apt update && \
            sudo apt install -y apt-transport-https && \
            sudo apt update && \
            sudo apt install -y dotnet-sdk-3.1

      - name: Install Azure Data Studio
        run: |
          curl -Lo azuredatastudio-linux.deb https://go.microsoft.com/fwlink/?linkid=2168339
          sudo dpkg -i azuredatastudio-linux.deb
          sudo rm -rf azuredatastudio-linux.deb
          sudo apt install -y libunwind8
          
          echo "NET_CORE_TARGETS_PATH=/usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/$(ls /usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/ | head -n1)" >> $GITHUB_ENV

      - name: Build dacpac
        run: dotnet build "${AZURE_DATA_STUDIO_PROJECT_PATH}" /p:NetCoreBuild=true /p:NETCoreTargetsPath="${NET_CORE_TARGETS_PATH}"
        
      - name: Upload .dacpac
        uses: actions/upload-artifact@v2
        with:
          name: dacpac
          path: ${{ env.DACPAC_PATH }}
