name: ci-synapse

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'synapse/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: synapse-via
      ENVIRONMENT_PREFIX: dev
      PROFILE_PATH: ${{ github.workspace }}/synapse/profiles/${{ env.ENVIRONMENT_PREFIX }}.publish.xml
      PROJECT_PATH: ${{ github.workspace }}/synapse/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.sqlproj
      REPORT_PATH: ${{ github.workspace }}/synapse/${{ env.PROJECT_NAME }}
      DACPAC_PATH: ${{ github.workspace }}/synapse/${{ env.PROJECT_NAME }}/bin/Debug/${{ env.PROJECT_NAME }}.dacpac

    steps:
      - uses: actions/checkout@v2

      - name: Install sqlpackage
        run: |
          curl -Lo sqlpackage-linux.zip https://aka.ms/sqlpackage-linux
          unzip -o sqlpackage-linux.zip -d /opt/sqlpackage/
          chmod +x /opt/sqlpackage/*
          sudo rm -f /bin/sqlpackage
          sudo ln -s /opt/sqlpackage/sqlpackage /bin/sqlpackage
          sudo rm -rf sqlpackage-linux.zip

      - name: Install dotnet
        run: |
          wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
          sudo dpkg -i packages-microsoft-prod.deb && \
          rm packages-microsoft-prod.deb

          sudo apt update && \
            sudo apt install -y apt-transport-https && \
            sudo apt update && \
            sudo apt install -y dotnet-sdk-3.1

      - name: Install Azure Data Studio
        run: |
          curl -Lo azuredatastudio-linux.deb https://go.microsoft.com/fwlink/?linkid=2168339
          sudo dpkg -i azuredatastudio-linux.deb
          sudo rm -rf azuredatastudio-linux.deb
          sudo apt install -y libunwind8
          
          echo "NET_CORE_TARGETS_PATH=/usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/$(ls /usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/ | head -n1)" >> $GITHUB_ENV

      - name: Build dacpac
        run: dotnet build "${AZURE_DATA_STUDIO_PROJECT_PATH}" /p:NetCoreBuild=true /p:NETCoreTargetsPath="${NET_CORE_TARGETS_PATH}"
        
      - name: Upload .dacpac
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.DACPAC_PATH }}

      - name: Scheme compare
        run: |
          mkdir -p "${REPORT_PATH}"
          
          # Export deploy report
          sqlpackage \
            /Action:DeployReport \
            /Profile:"${PROFILE_PATH}" \
            /OutputPath:"${REPORT_PATH}/deploy_report.xml" \
            /OverwriteFiles:True \
            /SourceFile:"${DACPAC_PATH}" \
            /TargetDatabaseName:${{ secrets.SERVER_DATABASE }} \
            /TargetPassword:"${{ secrets.SERVER_PASSWD }}" \
            /TargetServerName:${{ secrets.SERVER_PASSWD }} \
            /TargetUser:${{ secrets.SERVER_USER_ID }}

          # Export sql script
          sqlpackage \
            /Action:Script \
            /Profile:"${PROFILE_PATH}" \
            /OutputPath:"${REPORT_PATH}/deploy.sql" \
            /OverwriteFiles:True \
            /SourceFile:"${DACPAC_PATH}" \
            /TargetDatabaseName:${{ secrets.SERVER_DATABASE }} \
            /TargetPassword:"${{ secrets.SERVER_PASSWD }}" \
            /TargetServerName:${{ secrets.SERVER_PASSWD }} \
            /TargetUser:${{ secrets.SERVER_USER_ID }}

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ${{ env.REPORT_PATH }}


  deploy:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: build
      ENVIRONMENT_PREFIX: dev
      PROFILE_PATH: ${{ github.workspace }}/synapse/profiles/${{ env.ENVIRONMENT_PREFIX }}.publish.xml

    steps:
      - uses: actions/checkout@v2

      - name: Install sqlpackage
        run: |
          curl -Lo sqlpackage-linux.zip https://aka.ms/sqlpackage-linux
          unzip -o sqlpackage-linux.zip -d /opt/sqlpackage/
          chmod +x /opt/sqlpackage/*
          sudo rm -f /bin/sqlpackage
          sudo ln -s /opt/sqlpackage/sqlpackage /bin/sqlpackage
          sudo rm -rf sqlpackage-linux.zip

      - name: Download .dacpac
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - name: Publish .dacpac
        run: |
          DACPAC_PATH=$(find ${{ env.ARTIFACT_NAME }} -name '*.dacpac')
          
          sqlpackage \
            /Action:Publish \
            /Profile:"${PROFILE_PATH}" \
            /SourceFile:"${DACPAC_PATH}" \
            /TargetDatabaseName:${{ secrets.SERVER_DATABASE }} \
            /TargetPassword:"${{ secrets.SERVER_PASSWD }}" \
            /TargetServerName:${{ secrets.SERVER_PASSWD }} \
            /TargetUser:${{ secrets.SERVER_USER_ID }}
