name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install sqlpackage
        run: |
          curl -Lo sqlpackage-linux.zip https://aka.ms/sqlpackage-linux
          unzip -o sqlpackage-linux.zip -d /opt/sqlpackage/
          chmod +x /opt/sqlpackage/*
          sudo rm -f /bin/sqlpackage
          sudo ln -s /opt/sqlpackage/sqlpackage /bin/sqlpackage
          sudo rm -rf sqlpackage-linux.zip

      - name: Test sqlpackage
        run: sqlpackage
